--------------------------------------------------------
--  파일이 생성됨 - 화요일-8월-08-2023   
--------------------------------------------------------
DROP TABLE "JACSOMUNG"."MEMBER_TBL" cascade constraints;
DROP TABLE "JACSOMUNG"."NOTICE_TBL" cascade constraints;
DROP TABLE "JACSOMUNG"."QUESTION_BOARD_TBL" cascade constraints;
--------------------------------------------------------
--  DDL for Table MEMBER_TBL
--------------------------------------------------------

  CREATE TABLE "JACSOMUNG"."MEMBER_TBL" 
   (	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"MEMBER_PW" VARCHAR2(20 BYTE), 
	"MEMBER_NAME" VARCHAR2(20 BYTE), 
	"MEMBER_EMAIL" VARCHAR2(30 BYTE), 
	"MEMBER_PHONE" VARCHAR2(11 BYTE), 
	"MEMBER_ADDRESS" VARCHAR2(500 BYTE), 
	"JOINDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTICE_TBL
--------------------------------------------------------

  CREATE TABLE "JACSOMUNG"."NOTICE_TBL" 
   (	"NOTICE_NO" NUMBER, 
	"NOTICE_SUBJECT" VARCHAR2(50 BYTE), 
	"NOTICE_CONTENT" VARCHAR2(1000 BYTE), 
	"NOTICE_WRITER" VARCHAR2(50 BYTE), 
	"WRITEDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QUESTION_BOARD_TBL
--------------------------------------------------------

  CREATE TABLE "JACSOMUNG"."QUESTION_BOARD_TBL" 
   (	"BOARD_NO" NUMBER, 
	"BOARD_SUBJECT" VARCHAR2(50 BYTE), 
	"BOARD_CONTENT" VARCHAR2(1000 BYTE), 
	"BOARD_WRITER" VARCHAR2(50 BYTE), 
	"BOARD_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JACSOMUNG.MEMBER_TBL
SET DEFINE OFF;
Insert into JACSOMUNG.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_EMAIL,MEMBER_PHONE,MEMBER_ADDRESS,JOINDATE) values ('khuser01','pass01','일용자','khuser01@naber.com','01011112222','서울시 동대문구',to_date('23/07/30','RR/MM/DD'));
Insert into JACSOMUNG.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_EMAIL,MEMBER_PHONE,MEMBER_ADDRESS,JOINDATE) values ('user22','pass22','이용자','user22@hanmail.net','01088887777','강원도 속초시',to_date('23/08/03','RR/MM/DD'));
REM INSERTING into JACSOMUNG.NOTICE_TBL
SET DEFINE OFF;
Insert into JACSOMUNG.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,WRITEDATE) values (1,'설연휴 배송안내','설연휴 배송안내','admin',to_date('23/08/03','RR/MM/DD'));
Insert into JACSOMUNG.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,WRITEDATE) values (2,'배송 지연안내','배송 지연안내','admin',to_date('23/08/03','RR/MM/DD'));
REM INSERTING into JACSOMUNG.QUESTION_BOARD_TBL
SET DEFINE OFF;
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (1,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (2,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (3,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (4,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (5,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (6,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (7,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (8,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (9,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (10,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (11,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (12,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (13,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (14,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (15,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (16,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (17,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (18,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (19,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (20,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (21,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (22,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (23,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (24,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (25,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (26,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (27,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (28,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (29,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (30,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (31,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (32,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (33,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (34,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (35,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (36,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (37,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (38,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (39,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (40,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (41,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (42,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (43,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (44,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (45,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (46,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (47,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (48,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (49,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
Insert into JACSOMUNG.QUESTION_BOARD_TBL (BOARD_NO,BOARD_SUBJECT,BOARD_CONTENT,BOARD_WRITER,BOARD_DATE) values (50,'상품 문의','상품 문의 내용','김아름',to_date('23/08/07','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "JACSOMUNG"."PK_MEMBER" ON "JACSOMUNG"."MEMBER_TBL" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007223
--------------------------------------------------------

  CREATE UNIQUE INDEX "JACSOMUNG"."SYS_C007223" ON "JACSOMUNG"."NOTICE_TBL" ("NOTICE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007227
--------------------------------------------------------

  CREATE UNIQUE INDEX "JACSOMUNG"."SYS_C007227" ON "JACSOMUNG"."QUESTION_BOARD_TBL" ("BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER_TBL
--------------------------------------------------------

  ALTER TABLE "JACSOMUNG"."MEMBER_TBL" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JACSOMUNG"."MEMBER_TBL" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "JACSOMUNG"."MEMBER_TBL" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE_TBL
--------------------------------------------------------

  ALTER TABLE "JACSOMUNG"."NOTICE_TBL" ADD PRIMARY KEY ("NOTICE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JACSOMUNG"."NOTICE_TBL" MODIFY ("NOTICE_WRITER" NOT NULL ENABLE);
  ALTER TABLE "JACSOMUNG"."NOTICE_TBL" MODIFY ("NOTICE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "JACSOMUNG"."NOTICE_TBL" MODIFY ("NOTICE_SUBJECT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUESTION_BOARD_TBL
--------------------------------------------------------

  ALTER TABLE "JACSOMUNG"."QUESTION_BOARD_TBL" ADD PRIMARY KEY ("BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JACSOMUNG"."QUESTION_BOARD_TBL" MODIFY ("BOARD_WRITER" NOT NULL ENABLE);
  ALTER TABLE "JACSOMUNG"."QUESTION_BOARD_TBL" MODIFY ("BOARD_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "JACSOMUNG"."QUESTION_BOARD_TBL" MODIFY ("BOARD_SUBJECT" NOT NULL ENABLE);
